from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "PROJECT_GRAPHS.md"


def build_markdown() -> str:
    return """# Project Graphs

This document was generated by `graphify_projects.py` from the current workspace layout.

## Workspace Overview

```mermaid
flowchart TD
    workspace["SDP Workspace"]
    workspace --> combined["combined/\\nUnified Flask app"]
    workspace --> handwriting["handwriting/\\nHandwriting detector"]
    workspace --> speech["speech/\\nSpeech detector"]
    workspace --> fusion["fusion_models/\\nCross-modal fusion detector"]

    combined --> c_app["app.py"]
    combined --> c_tpl["templates/index.html"]
    combined --> c_ckpt["Local .pth checkpoints"]

    handwriting --> h_app["app.py"]
    handwriting --> h_tpl["templates/index.html"]
    handwriting --> h_ckpt["MLP/CNN weights + scaler/meta model"]

    speech --> s_app["app.py"]
    speech --> s_tpl["templates/index.html"]
    speech --> s_ckpt["5-fold audio weights + scaler"]

    fusion --> f_app["app.py"]
    fusion --> f_tpl["templates/index.html"]
    fusion --> f_ckpt["Fusion/audio/handwriting checkpoints"]
```

## Handwriting Project

```mermaid
flowchart LR
    user["User image or canvas input"]
    route["POST /predict"]
    preprocess["OpenCV preprocessing\\nGrayscale + thresholding"]
    features["16 spatial biomarkers\\nextract_16_features()"]
    mlp["5x Residual MLP ensemble"]
    image_model["EfficientNet-B0 + CBAM\\n5 folds + optional TTA"]
    stack["Logistic regression meta-learner"]
    result["Prediction JSON\\nRisk, warnings, confidence"]
    ui["GET / -> templates/index.html"]
    health["GET /health"]

    user --> route
    route --> preprocess
    preprocess --> features
    features --> mlp
    preprocess --> image_model
    mlp --> stack
    image_model --> stack
    stack --> result
    ui -. serves .-> route
    health -. status .-> result
```

## Speech Project

```mermaid
flowchart LR
    user["Uploaded or recorded audio"]
    route["POST /predict"]
    save["uploads/ + secure filename"]
    prep["Resample, trim, normalize"]
    wav["XLS-R embeddings + BiLSTM"]
    mel["Mel-spectrogram CNN"]
    mfcc["MFCC + delta encoder"]
    acoustic["Acoustic voice features"]
    fusion["Multi-head cross-attention fusion"]
    clf["Classifier + 5-fold ensemble"]
    result["Prediction JSON\\nLabel, probability, diagnostics"]
    ui["GET / -> templates/index.html"]
    health["GET /health"]

    user --> route
    route --> save
    save --> prep
    prep --> wav
    prep --> mel
    prep --> mfcc
    prep --> acoustic
    wav --> fusion
    mel --> fusion
    mfcc --> fusion
    acoustic --> fusion
    fusion --> clf
    clf --> result
    ui -. serves .-> route
    health -. status .-> result
```

## Fusion Models Project

```mermaid
flowchart LR
    user["Image + audio input"]
    route["POST /predict"]
    img_prep["Image preprocessing\\nAlbumentations + tensor conversion"]
    aud_prep["Audio preprocessing\\nWaveform + handcrafted features"]
    hw_enc["Handwriting encoder\\nEfficientNet-B4 + CBAM + SPP"]
    aud_enc["Audio encoder\\nXLS-R + CNN + MFCC + acoustic blocks"]
    xattn["Cross-modal transformer attention"]
    gmu["GMU fusion head"]
    folds["5-fold fusion ensemble"]
    result["Prediction JSON\\nClass, confidence, uncertainty"]
    ui["GET / -> templates/index.html"]
    health["GET /health"]

    user --> route
    route --> img_prep
    route --> aud_prep
    img_prep --> hw_enc
    aud_prep --> aud_enc
    hw_enc --> xattn
    aud_enc --> xattn
    xattn --> gmu
    gmu --> folds
    folds --> result
    ui -. serves .-> route
    health -. status .-> result
```

## Combined Project

```mermaid
flowchart TD
    ui["combined/templates/index.html"]
    app["combined/app.py"]
    hw["POST /predict/handwriting"]
    sp["POST /predict/speech"]
    fu["POST /predict/fusion"]
    hw_pipe["Handwriting pipeline\\n16 features -> MLP/CNN -> stack"]
    sp_pipe["Speech pipeline\\nXLS-R/CNN/MFCC/acoustics -> ensemble"]
    fu_pipe["Fusion pipeline\\nHW encoder + audio encoder -> transformer + GMU"]
    json["JSON responses"]
    health["GET /health"]

    ui --> app
    app --> hw
    app --> sp
    app --> fu
    hw --> hw_pipe
    sp --> sp_pipe
    fu --> fu_pipe
    hw_pipe --> json
    sp_pipe --> json
    fu_pipe --> json
    health -. status .-> json
```

## Deployment View

```mermaid
flowchart TB
    render["Render deployment"]
    proc["Procfile"]
    yaml["render.yaml"]
    flask["Gunicorn + Flask app"]
    weights["Local checkpoint files (.pth/.pkl)"]
    template["templates/index.html"]

    render --> proc
    render --> yaml
    proc --> flask
    yaml --> flask
    flask --> template
    flask --> weights
```
"""


def main() -> None:
    OUTPUT.write_text(build_markdown(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
